//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.15 at 11:48:59 PM CAT 
//


package com.example.ehospital;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Added" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Medecine" type="{http://example.com/ehospital}MedecineDetails"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "added",
    "message",
    "medecine"
})
@XmlRootElement(name = "AddMedecineResponse")
public class AddMedecineResponse {

    @XmlElement(name = "Added")
    protected boolean added;
    @XmlElement(required = true)
    protected String message;
    @XmlElement(name = "Medecine", required = true)
    protected MedecineDetails medecine;

    /**
     * Gets the value of the added property.
     * 
     */
    public boolean isAdded() {
        return added;
    }

    /**
     * Sets the value of the added property.
     * 
     */
    public void setAdded(boolean value) {
        this.added = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the medecine property.
     * 
     * @return
     *     possible object is
     *     {@link MedecineDetails }
     *     
     */
    public MedecineDetails getMedecine() {
        return medecine;
    }

    /**
     * Sets the value of the medecine property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedecineDetails }
     *     
     */
    public void setMedecine(MedecineDetails value) {
        this.medecine = value;
    }

}
