//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.04 at 01:49:33 AM CAT 
//


package com.example.auth;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.auth package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.auth
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PatientRegisterRequest }
     * 
     */
    public PatientRegisterRequest createPatientRegisterRequest() {
        return new PatientRegisterRequest();
    }

    /**
     * Create an instance of {@link PatientRegisterResponse }
     * 
     */
    public PatientRegisterResponse createPatientRegisterResponse() {
        return new PatientRegisterResponse();
    }

    /**
     * Create an instance of {@link PatientDetails }
     * 
     */
    public PatientDetails createPatientDetails() {
        return new PatientDetails();
    }

    /**
     * Create an instance of {@link PhysicianRegisterRequest }
     * 
     */
    public PhysicianRegisterRequest createPhysicianRegisterRequest() {
        return new PhysicianRegisterRequest();
    }

    /**
     * Create an instance of {@link PhysicianRegisterResponse }
     * 
     */
    public PhysicianRegisterResponse createPhysicianRegisterResponse() {
        return new PhysicianRegisterResponse();
    }

    /**
     * Create an instance of {@link PhysicianDetails }
     * 
     */
    public PhysicianDetails createPhysicianDetails() {
        return new PhysicianDetails();
    }

    /**
     * Create an instance of {@link PharmacistRegisterRequest }
     * 
     */
    public PharmacistRegisterRequest createPharmacistRegisterRequest() {
        return new PharmacistRegisterRequest();
    }

    /**
     * Create an instance of {@link PharmacistRegisterResponse }
     * 
     */
    public PharmacistRegisterResponse createPharmacistRegisterResponse() {
        return new PharmacistRegisterResponse();
    }

    /**
     * Create an instance of {@link PharmacistDetails }
     * 
     */
    public PharmacistDetails createPharmacistDetails() {
        return new PharmacistDetails();
    }

    /**
     * Create an instance of {@link AuthRequest }
     * 
     */
    public AuthRequest createAuthRequest() {
        return new AuthRequest();
    }

    /**
     * Create an instance of {@link AuthResponse }
     * 
     */
    public AuthResponse createAuthResponse() {
        return new AuthResponse();
    }

    /**
     * Create an instance of {@link PhysicianAuthRequest }
     * 
     */
    public PhysicianAuthRequest createPhysicianAuthRequest() {
        return new PhysicianAuthRequest();
    }

    /**
     * Create an instance of {@link PhysicianAuthResponse }
     * 
     */
    public PhysicianAuthResponse createPhysicianAuthResponse() {
        return new PhysicianAuthResponse();
    }

    /**
     * Create an instance of {@link GetAllPhysiciansRequest }
     * 
     */
    public GetAllPhysiciansRequest createGetAllPhysiciansRequest() {
        return new GetAllPhysiciansRequest();
    }

    /**
     * Create an instance of {@link AuthorizationHeader }
     * 
     */
    public AuthorizationHeader createAuthorizationHeader() {
        return new AuthorizationHeader();
    }

    /**
     * Create an instance of {@link GetAllPhysiciansResponse }
     * 
     */
    public GetAllPhysiciansResponse createGetAllPhysiciansResponse() {
        return new GetAllPhysiciansResponse();
    }

    /**
     * Create an instance of {@link GetAllPharmacistsRequest }
     * 
     */
    public GetAllPharmacistsRequest createGetAllPharmacistsRequest() {
        return new GetAllPharmacistsRequest();
    }

    /**
     * Create an instance of {@link GetAllPharmacistsResponse }
     * 
     */
    public GetAllPharmacistsResponse createGetAllPharmacistsResponse() {
        return new GetAllPharmacistsResponse();
    }

    /**
     * Create an instance of {@link SelectPhysicianRequest }
     * 
     */
    public SelectPhysicianRequest createSelectPhysicianRequest() {
        return new SelectPhysicianRequest();
    }

    /**
     * Create an instance of {@link SelectPhysicianResponse }
     * 
     */
    public SelectPhysicianResponse createSelectPhysicianResponse() {
        return new SelectPhysicianResponse();
    }

    /**
     * Create an instance of {@link GiveConsultationRequest }
     * 
     */
    public GiveConsultationRequest createGiveConsultationRequest() {
        return new GiveConsultationRequest();
    }

    /**
     * Create an instance of {@link GiveConsultationResponse }
     * 
     */
    public GiveConsultationResponse createGiveConsultationResponse() {
        return new GiveConsultationResponse();
    }

    /**
     * Create an instance of {@link PatientConsultation }
     * 
     */
    public PatientConsultation createPatientConsultation() {
        return new PatientConsultation();
    }

}
